name: Dependency Upgrade Bot

on:
  workflow_dispatch:

jobs:

  build-matrix:

    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}

    steps:

      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq -y

      - id: matrix
        run: |

          MATRIX=$(jq -c '
            [
              .dependencies[] as $d
              | $d.repos[]
              | {
                  repo: .,
                  property: $d.property,
                  version: $d.version
                }
            ] | {include:.}
          ' dependency-versions.json)

          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  upgrade:

    needs: build-matrix
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}

    steps:

      - name: Configure Git Auth
        run: |
          git config --global url."https://x-access-token:${{ secrets.DOWNSTREAM_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Clone repo
        run: |
          git clone https://github.com/anikgupta1970/${{ matrix.repo }}.git

      - name: Update dependency
        run: |
          cd ${{ matrix.repo }}

          mvn versions:set-property \
            -Dproperty=${{ matrix.property }} \
            -DnewVersion=${{ matrix.version }} \
            -DgenerateBackupPoms=false

      - name: Commit changes
        run: |
          cd ${{ matrix.repo }}

          git checkout -b chore/upgrade-${{ matrix.property }}-${{ matrix.version }}

          git config user.name "dependency-bot"
          git config user.email "bot@company.com"

          git commit -am "chore: upgrade ${{ matrix.property }} to ${{ matrix.version }}" || echo "No changes"

          git push origin HEAD

      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.DOWNSTREAM_PAT }}
        run: |
          cd ${{ matrix.repo }}

          gh pr create \
            --title "Upgrade ${{ matrix.property }} to ${{ matrix.version }}" \
            --body "Automated dependency upgrade"
